image: docker:git

stages:
  - mirror
  - build

variables:
  MEDSPACE_IMAGE: $CI_REGISTRY/mclibrary/medspace
  FCREPO_IMAGE: $CI_REGISTRY/mclibrary/medspace/fcrepo
  SOLR_IMAGE: $CI_REGISTRY/mclibrary/medspace/solr

github_mirror:
  stage: mirror
  allow_failure: true
  script:
    - cd /tmp
    - git clone --bare $CI_REPOSITORY_URL
    - cd medspace.git
    - git push --mirror https://$GITHUB_TOKEN@github.com/dumclibrary/medspace.git

medspace_build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $MEDSPACE_IMAGE .
    - docker push $MEDSPACE_IMAGE
  only:
    - master

fcrepo_build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $FCREPO_IMAGE docker-fcrepo
    - docker push $FCREPO_IMAGE
  only:
    - master

solr_build:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
  script:
    - docker build -t $SOLR_IMAGE solr
    - docker push $SOLR_IMAGE
  only:
    - master