terms:
  - id: Artifact
    term: Artifact
  - id: Article
    term: Article
  - id: Artwork
    term: Artwork
  - id: Audio
    term: Audio
  - id: Correspondence
    term: Correspondence
  - id: Image
    term: Image
  - id: Poster
    term: Poster
  - id: Presentation
    term: Presentation
  - id: Publication
    term: Publication
  - id: Video
    term: Video
  - id: Other
    term: Other
