terms:
  - id: Image
    term: Image
  - id: Article
    term: Article
  - id: Artifact
    term: Artifact
  - id: Book
    term: Book
  - id: Journal
    term: Journal
  - id: Part of Book
    term: Part of Book
  - id: Poster
    term: Poster
  - id: Presentation
    term: Presentation
  - id: Other
    term: Other
#  - id: Audio
#    term: Audio
#  - id: Capstone Project
#    term: Capstone Project
#  - id: Conference Proceeding
#    term: Conference Proceeding
#  - id: Dataset
#    term: Dataset
#  - id: Dissertation
#    term: Dissertation
#  - id: Map or Cartographic Material
#    term: Map or Cartographic Material
#  - id: Masters Thesis
#    term: Masters Thesis
#  - id: Project
#    term: Project
#  - id: Report
#    term: Report
#  - id: Research Paper
#    term: Research Paper
#  - id: Software or Program Code
#    term: Software or Program Code
#  - id: Video
#    term: Video
