#config/solr_wrapper_test.yml
# version: 6.1.0
port: 8985
instance_dir: tmp/solr-test
collection:
    persist: false
    dir: solr/config
    name: hydra-test
url: https://archive.apache.org/dist/lucene/solr/6.6.0/solr-6.6.0.zip
validate: false

